### ISSUE TITLE
Sample metadata file?

### ISSUE THREAD

**Issue by adityabandla** [defleury/Schmidt_et_al_2016_community_similarity#4]
Hi 

I am trying to reproduce the analysis stated in the article. However, I am missing the sample metadata file in the data folder

Can you please make that available?

Best,
Aditya

**Comment by adityabandla** [comment]
I got the file from http://meringlab.org/suppdata/2016-community_similarity/data/sample_data.raw.tsv

Requesting if PARAM$file.sample_list is just the list of sample names from the above file?

**Comment by defleury** [comment]
Hi Aditya,

yes, that file would just be the first column of the first metadata file (sample names).

Sorry about the confusion. The code uploaded here was indeed put together from larger (and rather messy) analysis scripts which had grown organically throughout the project. We have recently tried a clean re-run on a different system and fixed a few issues. If you encounter further problems, please let me know; I'll do my best to provide quick fixes. The idea is to get an independent package to compute TINA/PINA in the near future, but that is still work in progress.

**Comment by adityabandla** [comment]
Hi Sebastian

Thanks for the quick reply! Indeed, it would be great to have a streamlined R package to implement TINA/PINA

I got through the first few lines of code, but got stuck with this error, prior to building the phyloseq object

colnames(ot.raw) <- paste("SN_", samples.raw, sep="")
Error in dimnamesGets(x, value) : 
invalid dimnames given for “dgCMatrix” object

**Comment by defleury** [comment]
Did you load `library("Matrix")`?

**Comment by adityabandla** [comment]
yes,I did

**Comment by adityabandla** [comment]
I just noticed that there are 5033 sample names in the metadata file, while only 4448 in the otu table

**Comment by defleury** [comment]
Hi,

I just added a commit w/ the respective sample files (metadata and pre-filtered list). I was wrong: the sample list was, after all, not just the first column, but a (filtered) list of all HMP samples for which v35 16S rRNA data was available/reasonable at the time (and for which OTUs had been called).

Also, I re-set the file paths relative to the repository, so that it should now work from the repo path directly.
