### ISSUE TITLE
p-value thresholding for correlations?

### ISSUE THREAD

**Issue by adityabandla** [defleury/Schmidt_et_al_2016_community_similarity#5]
Hi

Is there any particular reason that you dont compute p-values for the sparcc correlations? Why not just include the significant correlations for computing TINA/PINA?

Regards,
Aditya

**Comment by defleury** [comment]
Hi Aditya,

there are two points here. For the HMP dataset, I did some tests and found that the SparCC values were quite robust. To not only include significant correlations is a design choice for the time being: to calculate all pairwise SparCC correlations, and from these all pairwise derived correlations seems to be the most "exact" approach possible. Reducing the number of pairwise correlations to take into account (to also improve speed and efficiency) is something I'd very much like to try out, but so far haven't found the time to do.

Best,


Sebastian
